apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: jenkins-agent
  name: jenkins-agent
spec:
  ttlSecondsAfterFinished: 3600
  restartPolicy: Never
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:jdk17
      tty: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          cpu: "500m"
          ephemeral-storage: "2Gi"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
      env:
        - name: HOME
          value: /home/jenkins/agent

    - name: java
      image: openjdk:17.0.1-jdk-slim
      command:
        - "sleep"
        - "infinity"
      imagePullPolicy: Always
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          cpu: "500m"
          ephemeral-storage: "2Gi"
      env:
        - name: HOME
          value: /home/jenkins/agent
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: oc-tools
      image: image-registry.openshift-image-registry.svc:5000/kallepelli-rupesh-dev/oc-tools
      command:
        - "sleep"
        - "infinity"
      tty: true
      env:
        - name: HOME
          value: /home/jenkins/agent
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

  volumes:
    - name: workspace-volume
      emptyDir: {}
