apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent
spec:
  ttlSecondsAfterFinished: 3600
  restartPolicy: Never
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  - name: java
    image: openjdk:17.0.1-jdk-slim
    command: 
      - cat
    imagePullPolicy: Always
  volumes:
  - name: workspace-volume
    emptyDir: {}
