apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent
spec:
  ttlSecondsAfterFinished: 3600
  restartPolicy: Never
  runAsUser: 0
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.13.3-1
      tty: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          cpu: "500m"
          ephemeral-storage: "2Gi"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: java
      image: openjdk:17.0.1-jdk-slim
      command:
        - "sleep"
        - "infinity"
      imagePullPolicy: Always
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          cpu: "500m"
          ephemeral-storage: "2Gi"
  volumes:
    - name: workspace-volume
      emptyDir: {}
