apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ${appName}-build
  namespace: ${namespace}
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile       
  output:
    to:
      kind: ImageStreamTag
      name: "${appName}:${appVersion}"
