apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_URL: jdbc:mysql://donationsdb-donationsdb.k.aivencloud.com:26204/defaultdb
  DB_USERNAME: avnadmin
  DB_PASSWORD: AVNS_WYMwYsaLHWuW49H-HsG
  DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  DB_DIALECT: org.hibernate.dialect.MySQL8Dialect
