apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUi.image }}"
          ports:
            - containerPort: {{ .Values.kafkaUi.port }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "{{ .Values.kafkaUi.clusterName }}"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka1:29091,kafka2:29092,kafka3:29093"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper:2181"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "http://schema-registry:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  ports:
    - port: {{ .Values.kafkaUi.port }}
      targetPort: {{ .Values.kafkaUi.port }}
  selector:
    app: kafka-ui
