apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
        - name: ksqldb
          image: confluentinc/ksqldb-server:0.29.0
          ports:
            - containerPort: 8088
          volumeMounts:
            # Mounting the config files to /etc/ksqldb
            - name: config-volume
              mountPath: /etc/ksqldb
            # Mounting the logs directory to /etc/ksqldb/logs
            - name: logs-volume
              mountPath: /etc/ksqldb/logs
          env:
            - name: KSQL_LISTENER
              value: "http://0.0.0.0:8088"
            - name: KSQL_KSQL_SERVICE_ID
              value: "ksql-service"
      volumes:
        - name: config-volume
          configMap:
            name: ksqldb-config # ConfigMap with the necessary configuration files
        - name: logs-volume
          emptyDir: {}  # Logs volume (or you can use PVC for persistence)
