{{- if .Values.routes.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  to:
    kind: Service
    name: schema-registry
  port:
    targetPort: 8081
  tls:
    termination: edge
{{- end }}
