{{- if .Values.routes.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  to:
    kind: Service
    name: zookeeper
  port:
    targetPort: 2181
  tls:
    termination: edge
{{- end }}
