spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                exposed-headers:
                  - Authorization
                  - Content-Type
                allow-credentials: false
          routes:
            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=/users/**
            - id: persistence-service
              uri: http://persistence-service:8080
              predicates:
                - Path=/persistence/**
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: user-service
        url: http://user-service:8080/v3/api-docs
      - name: persistence-service
        url: http://persistence-service:8080/v3/api-docs
server:
  port: 8080