spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: user-service-api-docs
          uri: http://user-service:8080
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - RewritePath=/users/v3/api-docs, /v3/api-docs
        - id: persistence-service
          uri: http://persistence:8080
          predicates:
            - Path=/persistence/**
          filters:
            - StripPrefix=1
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: user-service
        url: /users/v3/api-docs
      - name: persistence-service
        url: /persistence/v3/api-docs
server:
  port: 8080