apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: jenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/instance: jenkins
    spec:
      serviceAccountName: {{ .Values.master.serviceAccount.name }}
      containers:
        - name: jenkins
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          env:
            - name: JENKINS_ADMIN_ID
              value: "{{ .Values.master.adminUser }}"
            - name: JENKINS_ADMIN_PASSWORD
              value: "{{ .Values.master.adminPassword }}"
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_home/casc-config/casc.yaml
          ports:
            - containerPort: 8080
            - containerPort: 50000
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: casc-config
              mountPath: /var/jenkins_home/casc-config
            - name: plugins-list
              mountPath: /usr/share/jenkins/ref/plugins.txt
              subPath: plugins.txt
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: casc-config
          configMap:
            name: jenkins-casc
        - name: plugins-list
          configMap:
            name: plugins-list
