apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: jenkins
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: agent
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: jenkins
  type: {{ .Values.master.service.type }}
