kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    storageClassName: "gp3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.namespace}}
  name: jenkins-artifact-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3

    