apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: oc-tools-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/rupesh-kallepelli/donation-portal.git
    contextDir: oc-images/docker
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: oc-tools:latest
