apiVersion: v2
name: kafka
description: A Helm chart for deploying Zookeeper, Kafka, Schema Registry, and related services
version: 0.1.0
appVersion: "7.5.0"
icon: https://kafka.apache.org/images/favicon.png
