replicaCount: 1

zookeeper:
  image: "confluentinc/cp-zookeeper:7.5.0"
  containerPort: 2181
  clientPort: 2181
  tickTime: 2000

kafka:
  image: "confluentinc/cp-kafka:7.5.0"
  replicas: 3
  listeners:
    internal: "PLAINTEXT"
    external: "PLAINTEXT"
  advertisedListeners:
    internal: "localhost:29091"
    external: "localhost:9092"
  offsetsTopicReplicationFactor: 3
  brokerIds:
    - 1
    - 2
    - 3

schemaRegistry:
  image: "confluentinc/cp-schema-registry:7.5.0"
  port: 8081

ksqldb:
  image: "confluentinc/ksqldb-server:0.29.0"
  port: 8088
  serviceId: "ksql-service"

kafkaUi:
  image: "provectuslabs/kafka-ui:latest"
  port: 8080
  clusterName: "local"

routes:
  enabled: true
  zookeeper: true
  kafka1: true
  kafka2: true
  kafka3: true
  schemaRegistry: true
  ksqldb: true
  kafkaUi: true
